### ISSUE TITLE
Song.from_url crashes when there is no album art

### ISSUE THREAD

**Issue by quagsirus** [spotDL/spotdl-v4#21]
### System OS

Windows

### Python Version

3.9 (CPython)

### Install Source

GitHub

### Install version / commit hash

f017798

## Expected
Downloads song with no errors

## Actual
Crashes when downloading metadata, since it is trying to access an empty list

### Steps to reproduce

1. Install spotdl with the command `pip install -U https://codeload.github.com/spotDL/spotdl-v4/zip/master --force`
2. `spotdl download https://open.spotify.com/track/1yjqIsqGHebyfFO9WtEMAX --log-level DEBUG --simple-tui`

### Traceback

```text
12:39:17 - DEBUG - Downloader initialized
12:39:17 - DEBUG - Traceback (most recent call last):
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\site-packages\spotdl\console\download.py", line 37, in download
    results = downloader.download_multiple_songs(songs)
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\site-packages\spotdl\download\downloader.py", line 245, in download_multiple_songs
    results = list(self.loop.run_until_complete(self._aggregate_tasks(tasks)))
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\site-packages\spotdl\download\downloader.py", line 530, in _aggregate_tasks
    return await asyncio.gather(*(task for task in tasks))
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\site-packages\spotdl\download\downloader.py", line 278, in pool_download
    return await self.loop.run_in_executor(
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\site-packages\spotdl\download\downloader.py", line 350, in search_and_download
    new_data = Song.from_url(data["url"]).json
  File "C:\Users\quags\AppData\Local\Programs\Python\Python310\lib\site-packages\spotdl\types\song.py", line 106, in from_url
    cover_url=raw_album_meta["images"][0]["url"]
IndexError: list index out of range

12:39:17 - ERROR - list index out of range
```

**Comment by xnetcat** [comment]
https://github.com/spotDL/spotdl-v4/commit/48c04ea8b02beea065bf99e77891c12782255e83
